name: hydrated_mobx
description: 'An extension to the MobX state management library which automatically persists and restores MobX states.'
version: 1.1.2
homepage: https://github.com/NarekManukyan/hydrated_mobx
repository: https://github.com/NarekManukyan/hydrated_mobx.git
issue_tracker: https://github.com/NarekManukyan/hydrated_mobx/issues
documentation: https://github.com/NarekManukyan/hydrated_mobx#readme

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.14.0 <4.0.0'

dependencies:
  hive_ce: ^2.0.0
  meta: ^1.3.0
  mobx: ^2.5.0
  synchronized: ^3.0.0

dev_dependencies:
  build_runner: ^2.3.3
  collection: ^1.17.1
  crypto: ^3.0.2
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  mocktail: ^1.0.0
  path: ^1.8.3
  test: ^1.22.2
  uuid: ^3.0.7
